---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  encryptedData:
    password: AgCVMmeilWB6/C3ikTFhe0jsSYX/lBW0mDofqThPC9M0sDGI6iuHWORdrmGRuVU97oMTeHS3d1dHyr5UZ43XJql/H5sL+Dd1yddeOYXY5UjnnTc0qMRdfd9+oGN1gBdie+sTX1ZU4RlLwHU/Zdm7ZT1PU3dKC3R+nvVmyFdjpmmCe6uTXB+BBUMu6XDD7phHSO2xGaRNOS+HJ97HDf0vyWgEgKQqlNx2YABHzFeJnNvN+OK8oVsZP59KQzrYS8cOEK2eRBDfajL3yhqXLrFxbw2dgwqP/+Zh0WXw9ork6N0Zh+hRccKlxDCvKEl01xBLlhiYgjDMf/EsaH1V+QqsH8AwEoyu0KGAFh5XpbKSMU0NjiTl23bxejuQEExIwOUoYTitZYfk0k1vsr2RGr0dAaC9Hk9l0vhEFSI3+9MY5UhqkoBeBUV6IEa0fvzW3fwqR72nUTpkn2jZW/UKVC/O/KF5UvHziEQHoA8ZzLIiTqbbxgHsYIUFnqyn9kGyiPEPVPe0TXk8lKx8R7iIGYeWV9+SZL1z5YSnRibWpZGrJSP+KUK8mqRR2hvpYqrow5wMTlKGZDRrXR6BVPWKxpbb3/AxjJ+HVd9hr1racIU9vXJeGtBKZjh91KwiKHuCAVdm7h0zHENvgFNfVYwVoz+KYxD1hncr/zz7I1XG72UcNL02KKPv7LOiY9FH6X7PABgPDIZHjdlhe4Cj3Q==
    username: AgCaGHyyRnMyo3WXDaMZzejogsTRbyxEFbTtjLWMEYq2PViq6ZKm3GmtX80PqLIFMc9CR9IsqEl6BzbdJ6dpojsxh3On6cA+UGwGU826ZMupQCr3lnUoqmWe8vLjFQKV5k9a8iuPphjfd0bBps47l9PJ7jt9C2qSzv5tuwlz9Ri7caurBVFniKCEdwswlqckPwNCw1uNhrU7UdOXTPc0zTAoVqbx5+PO9lm2X8qamUSkyYsCoeUh+jUvSukSOgR6N6xzt8SDMybS82ou/J5HZ8oVhzYrWMRIkmiRy+dUUiEX2qBVVCIkkeGu2JuHjpihBtblL6k5bp3DpLyt+Dg9b8KownlF1L4eq7DbiASeEsUWQg1uQua32mHnseibZgurvdfF6rMfy1MnA9agTx7ZgXs5iKU0dg5fefFL3UA+DbaSWdVv9Luoo8lljhx3rQui8aL9NU5OVzRTzvb667ehBI+eX82zzZYmLh4qmO84vU1Heopqsr2RNjuKMTaedlDT3ZhWycTau0snoJvVs/wP+QVUx6G2gi/yYzSq50MD562GVK2Hd1eKjkx/5IVso3UnogHYjkS1LpaaKuFQEQ2cymHiN+brrqw8qi9ATFt40p2mfTvr8THDRhg8PtlH2W23YzBMs5Evl/L7M5+HUDRmGnwR84eLjkViYgClTh5nDaqAPK1bQb9mS8E0hXtvEdH3Um/pePRnGpZ2CA==
  template:
    metadata:
      name: keycloak-db
      namespace: keycloak
