---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBNW3bA4Z8K6xvCbmxhmgOqjSi00CPViMiUs97ho25BFd09Yd2ZtinKAG5dyK/z16wkxtwFWvdegCtLta/38bfMzNzzCYtf9yJE6YZ/VzTxSNKP4zqqC2HA+umjuLijBnPDCAIDM+cNmGQLZKOLBLucI9DWubq+sm7H/zC9pCf9CSz5uBhFgwUsiUtP3irYszTjfY2zsuCbRSzBeARdlnSI7kgqPctfHTGG1RfG0tR8veXwAoT2PFiecgrBhYGN5XB2Iwo0rTHLQYRCGQe0HeeHxFyy9lG9waAazQ0EGNq0LwKHnTSMeV9ojQmw+Yd3nDaaVr9rLIzVooZ2n1fT6Jdz4V/bTpRCW83uWO78z5vSZyDyebv9LALirWAfKiE4Xg7ZgFMdAfpxmoNi7w8LjDBgXkVRbuX2b5sRU862B8ZnQlmDoUgBrvQd47z8EgKaBnF40rUGgOQFjuIVeuhbpk7wCt4+6eliHdFEWU6XCaHLaE17clhFZngo+/+5I49H7ehBm1m9mMK2otO9Gu6GNHPJfuBr7RxxjrEA4VgQTB2nvS63TWTvbl2D7UZF8cOr7qdpcqlUt5Gk0FBpTDKJmCvDP/HmwubnSfNqfBaCollGGPoWBQUzjYuI8dT3DgmzQf5aP7d4VwHa1jaMmTewcjRGAr4Vn9QloNAB0PqZCzur4W4Dz4aVzE/hY8/uRJa9A7NhvleW0i6E7Gw0kuUQ+WHOCazJYBZ1nwgi2WegRDE7VQ==
  template:
    metadata:
      name: redis-auth
      namespace: redis
