---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redisinsight-secrets
  namespace: redis
spec:
  encryptedData:
    encryption-key: AgATp2w0NrUe/VFGBOjXcFUoCperY42BGULLh0Aa152Jjcq9lrO/rZahqIZp6SemyNuYw7lWm/bUNqDiYvdr8p0z6LpjaBMNs5tF3s/CPak/68lTIL7azs2Vb3lsby7RGhUofVP6rzogXR4ZXc4RoxG9otlxYEmLs6GdvGaaB9GOBlhQ3jhrU7HnlcC3GbTZho75xeBkZBDoc9X0UkFVIJEMBy9cnMwYExcXtlLoBQ0MY7NL8oA38PQpRNAomiQBiy6bjODA3LcHmDKVtMHi5QbHgC2GIcZfPnCJ9wAcgLWuiUnpdOvF98Wm7wPt6/B/RE+ExwKrYzF1PH8CXu8XwrGI2fnSCbS3BkCeHkuRx2suegBOhYa5DSKXCYLSwH7LCVffYSfY0i6WVTjfIV1K/cXcftr5sIo6UHVeEtUxTx/F+LfetK2Z5nBW7CkWu9C4cnqarz/HmYq2qvEeDN26y6jUIxB6BYSxVFzwxprZHiP1OsFoYK5thU7HOMKZjLO5t1lvMietp4MdqDEfT3b2LLaAkB4PCTTgFZI6NUo1CPLtjHnKfuNuArNry3n8pq/24pdunPapXellDVRlvzS3AtXKVRKot1FsU85myDopxxKTdv5jzyQGAnUjfuGpfFIOOXmCz/VtfMSPXx0hhBK7xiXIk7j30aSqrtVHVvHRRe7bGPksKq4I9n+UL5BXCpUNDl+KZexKXlHnAL4K5okRaI69Zkg3k3S4s5UGE5pt+xSyCQ==
  template:
    metadata:
      name: redisinsight-secrets
      namespace: redis
